p=r'C:\Users\magic\.copaw\workspaces\default\ethra_site\content\story\chapter-05.md'
d=open(p,encoding='utf-8').read()
print(len(d), 'bytes')
print('Pacing            =', d.count('**Pacing**'))
print('Strategy          =', d.count('**Strategy**'))
print('Lore Reveals      =', d.count('**Lore Reveals**'))
print('Emotional Core    =', d.count('**Emotional Core**'))
print('A Few Observations=', d.count('**A Few Observations**'))
print('Planning block    =', d.count("Let's start the next scene"))
print('correct dramatic  =', d.count('correct dramatic structure'))
print('battle logic holds=', d.count('battle logic holds'))
k=d.find('buried her face in Pearl')
v=d.find('It was 7:55 in the morning')
print()
print('Kira @',k)
print('7:55 @',v)
print('gap=',v-k,'bytes')
print()
print('--- TRANSITION CONTEXT (Kira + 200 bytes) ---')
print(repr(d[k:k+250]))
